default: bin/chess

bin/chess: create build/main.o build/board_print_plain.o build/board.o 
	gcc -Wall -Werror bin/chess -o build/main.o build/board_print_plain.o build/board.o 

build/main.o: create src/main.c
	gcc  -Wall -Werror src/main.c -o build/main.o    

build/board_print_plain.o: create src/board_print_plain.c src/board_print_plain.h
	gcc  -Wall -Werror src/board_print_plain.c -o build/board_print_plain.o

build/board.o: create src/board.c src/board.h
	gcc  -Wall -Werror src/board.c -o build/board.o

create:
	mkdir -p build
	mkdir -p bin

clean:
	rm -rf build bin
