CFLAGS = -Wall -Werror -std=c99
CC = gcc
OBJ = $(CC) -c -o  $(CFLAGS)




default: bin/chess create

create:
mkdir -p build
mkdir -р bin


bin/chess: build/main.o build/board_print_plain.o build/board.o 
	$(CC) $^ -o $@ $(CFLAGS)

build/main.o: src/main.c
	$(OBJ)

build/board_print_plain.o: src/board_print_plain.c src/board_print_plain.h
	$(OBJ)

build/board.o: src/board.c src/board.h
	$(OBJ)

clean:
rm -rf build bin
