default: create bin/chess

create:
mkdir -p build
mkdir -р bin


bin/chess: build/main.o build/board_print_plain.o build/board.o 
	gcc -Wall -Werror bin/chess -o build/main.o build/board_print_plain.o build/board.o 

build/main.o: src/main.c
	gcc -c -Wall -Werror src/main.c build/main.o

build/board_print_plain.o: src/board_print_plain.c src/board_print_plain.h
	gcc -c -Wall -Werror src/board_print_plain.c build/board_print_plain.o

build/board.o: src/board.c src/board.h
	gcc -c -Wall -Werror src/board.c build/board.o

clean:
rm -rf build bin
